services:
  model:
    build: 
      context: ./model
      args: 
        - AWS_DEFAULT_REGION=us-east-1
        - AWS_ACCESS_KEY_ID=${HOST_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${HOST_AWS_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"
      - "8081:8081"
    healthcheck:
      test: ["CMD" , "curl", "http://localhost:8080/ping"]
      timeout: 3m
    container_name: Model
  flask:
    build:
      context: ./flask
      args: 
        - AWS_DEFAULT_REGION=us-east-1
        - AWS_ACCESS_KEY_ID=${HOST_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${HOST_AWS_SECRET_ACCESS_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - model
    container_name: Flask
  frontend:
    build: ./frontend
    ports: 
      - "3000:80"
    depends_on:
      - flask
    container_name: Frontend

