version: "3"
services:
  model:
    build: ./model
    container_name: model
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  flask:
    build: ./flask
    depends_on:
      - model
    container_name: flask

  frontend:
    build: ./frontend
    ports: 
      - "80:80"
    depends_on:
      - flask
    container_name: frontend

