version: "3"
services:
  model:
    build: ./model
    ports:
      - "8080:8080"
      - "8081:8081"
    container_name: model

  flask:
    build: ./flask
    ports:
      - "5000:5000"
    depends_on:
      - model
    container_name: flask

  frontend:
    build: ./frontend
    ports: 
      - "80:80"
    depends_on:
      - flask
    container_name: frontend

